import { ReactNode, FC } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@components/components/NavBar/NavBar";
import Container from "@components/components/Container/Container";
import { AuthContextProvider } from "./context/AuthContext";
import { DialogContextProvider } from "./context/DialogContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootlayoutType = {
  children: ReactNode;
};

const RootLayout: FC<RootlayoutType> = ({ children }) => {
  return (
    <html lang="fr">
      <AuthContextProvider>
        <DialogContextProvider>
          <body className={inter.className}>
            <NavBar />
            <Container>{children}</Container>
          </body>
        </DialogContextProvider>
      </AuthContextProvider>
    </html>
  );
};

export default RootLayout;
